version: "3"

services:
  postgres:
    container_name: plutus-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - plutus
    volumes:
      - plutus-postgres-data:/var/lib/postgresql/data
    restart: always
  
  pgadmin:
    container_name: plutus-pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - plutus
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@wisecode.ai
      - PGADMIN_DEFAULT_PASSWORD=Welcometo2021!
    ports:
      - 5050:80
    volumes:
      - plutus-pgadmin-data:/var/lib/pgadmin

networks:
  plutus:
    driver: bridge 

volumes:
  plutus-postgres-data:
  plutus-pgadmin-data: