# flake8: noqa: W291
"""empty message

Revision ID: 8acadb0ca384
Revises: 
Create Date: 2022-07-08 14:12:14.360325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8acadb0ca384"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_instant", sa.DateTime(), nullable=True),
        sa.Column("updated_instant", sa.DateTime(), nullable=True),
        sa.Column("instant", sa.DateTime(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("bid", sa.Float(), nullable=True),
        sa.Column("ask", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trade",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_instant", sa.DateTime(), nullable=True),
        sa.Column("updated_instant", sa.DateTime(), nullable=True),
        sa.Column("event_instant", sa.DateTime(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trade_price",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("created_instant", sa.DateTime(), nullable=True),
        sa.Column("updated_instant", sa.DateTime(), nullable=True),
        sa.Column("price_id", sa.BigInteger(), nullable=False),
        sa.Column("trade_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["price.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trade.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trade_price")
    op.drop_table("trade")
    op.drop_table("price")
    # ### end Alembic commands ###
